// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knbldcvwdpavelmbmdre.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtuYmxkY3Z3ZHBhdmVsbWJtZHJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTQ0MDcsImV4cCI6MjA3MDA3MDQwN30.Cw3cnV4dj5eEN48AXMwxo2pps4Cj9IC-HXWFfydYyGc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});